-- TechOS Pro
-- Execute este arquivo no SQL Editor do Supabase.
-- Ele cria o modelo multiempresa, autenticação de perfil e RLS.

create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  company_id uuid not null references public.companies(id) on delete cascade,
  full_name text,
  role text not null default 'admin' check (role in ('admin','technician','attendant')),
  created_at timestamptz not null default now()
);

create table if not exists public.clients (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  phone text,
  email text,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  name text not null,
  price numeric(10,2) not null default 0,
  warranty text,
  description text,
  created_at timestamptz not null default now()
);

create sequence if not exists public.os_number_seq start 1001;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  number bigint not null default nextval('public.os_number_seq'),
  client_id bigint references public.clients(id) on delete set null,
  client_name text,
  client_phone text,
  device text not null,
  imei text,
  issue text,
  diagnosis text,
  password_notes text,
  accessories text,
  status text not null default 'pending' check (status in ('pending','in_progress','awaiting_part','completed','delivered','cancelled')),
  total numeric(10,2) not null default 0,
  warranty text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists clients_company_idx on public.clients(company_id);
create index if not exists services_company_idx on public.services(company_id);
create index if not exists orders_company_idx on public.orders(company_id);
create index if not exists orders_created_idx on public.orders(created_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  new_company uuid;
begin
  insert into public.companies(name)
  values (coalesce(nullif(new.raw_user_meta_data->>'company_name',''), 'Minha Assistência'))
  returning id into new_company;

  insert into public.profiles(id, company_id, full_name, role)
  values (
    new.id,
    new_company,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email,'@',1)),
    'admin'
  );

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.my_company_id()
returns uuid
language sql
stable
security definer
set search_path = public
as $$
  select company_id from public.profiles where id = auth.uid()
$$;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_touch_updated_at on public.orders;
create trigger orders_touch_updated_at
before update on public.orders
for each row execute procedure public.touch_updated_at();

alter table public.companies enable row level security;
alter table public.profiles enable row level security;
alter table public.clients enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;

drop policy if exists companies_select_own on public.companies;
create policy companies_select_own on public.companies
for select to authenticated
using (id = public.my_company_id());

drop policy if exists profiles_select_own_company on public.profiles;
create policy profiles_select_own_company on public.profiles
for select to authenticated
using (company_id = public.my_company_id());

drop policy if exists clients_all_own_company on public.clients;
create policy clients_all_own_company on public.clients
for all to authenticated
using (company_id = public.my_company_id())
with check (company_id = public.my_company_id());

drop policy if exists services_all_own_company on public.services;
create policy services_all_own_company on public.services
for all to authenticated
using (company_id = public.my_company_id())
with check (company_id = public.my_company_id());

drop policy if exists orders_all_own_company on public.orders;
create policy orders_all_own_company on public.orders
for all to authenticated
using (company_id = public.my_company_id())
with check (company_id = public.my_company_id());

-- Preenche automaticamente company_id em inserts feitos pelo app.
create or replace function public.set_company_id()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  new.company_id = public.my_company_id();
  return new;
end;
$$;

drop trigger if exists clients_set_company on public.clients;
create trigger clients_set_company before insert on public.clients for each row execute procedure public.set_company_id();

drop trigger if exists services_set_company on public.services;
create trigger services_set_company before insert on public.services for each row execute procedure public.set_company_id();

drop trigger if exists orders_set_company on public.orders;
create trigger orders_set_company before insert on public.orders for each row execute procedure public.set_company_id();

-- Serviços iniciais de exemplo serão criados automaticamente por empresa
-- quando o primeiro cadastro for feito, se desejado, pelo painel.
